services:
  volume-init:
    build:
      context: .
      dockerfile: shared-volume-init/Dockerfile
    env_file:
      - .env
    volumes:
      - shared-data:/shared-data

  audio-extractor:
    build:
      context: .
      dockerfile: audio-extractor/Dockerfile
    env_file:
      - .env
    environment:
      # Audio configuration
      - AUDIO_OUTPUT_MODE=chunks
      # Clock configuration
      - CLOCK_UPDATE_INTERVAL=1800
      - CLOCK_MAX_DRIFT=0.1
      - CLOCK_STATE_FILE=/shared-data/state/clock_state.json
      - CLOCK_SYNC_JITTER=60
    volumes:
      - shared-data:/shared-data
    depends_on:
      - volume-init
    restart: unless-stopped

  transcription-service:
    build:
      context: .
      dockerfile: transcription-service/Dockerfile
    env_file:
      - .env
    environment:
      - TRANSCRIPTION_LANGUAGE=ru
      # Clock configuration
      - CLOCK_UPDATE_INTERVAL=1800
      - CLOCK_MAX_DRIFT=0.1
      - CLOCK_STATE_FILE=/shared-data/state/clock_state.json
      # Offset calculation
      - OFFSET_WINDOW_SIZE=30
      - OFFSET_EMA_ALPHA=0.15
      - OFFSET_OUTLIER_THRESHOLD=2.5
      - OFFSET_MEDIAN_WEIGHT=0.4
      - OFFSET_STATE_FILE=/shared-data/state/offset_state.json
    volumes:
      - shared-data:/shared-data
    depends_on:
      - volume-init
      - audio-extractor
    restart: unless-stopped

  caption-generator:
    build:
      context: .
      dockerfile: caption-generator/Dockerfile
    env_file:
      - .env
    environment:
      # Timing parameters
      - BUFFER_DURATION=3
      - OFFSET_ADJUSTMENT_INTERVAL=30
      - DRIFT_THRESHOLD=0.5
      - WEBVTT_SEGMENT_DURATION=10
      - WEBVTT_SEGMENT_OVERLAP=1.0
      - WEBVTT_TIME_SOURCE=reference_clock
      - HLS_CLOCK_SYNC=true
      - SUBTITLE_DISPLAY_WINDOW=30
      - MINIMUM_CUE_DURATION=2.0
      # Clock configuration
      - CLOCK_UPDATE_INTERVAL=1800
      - CLOCK_MAX_DRIFT=0.1
      - CLOCK_STATE_FILE=/shared-data/state/clock_state.json
      # Offset calculation
      - OFFSET_WINDOW_SIZE=30
      - OFFSET_EMA_ALPHA=0.15
      - OFFSET_OUTLIER_THRESHOLD=2.5
      - OFFSET_MEDIAN_WEIGHT=0.4
      - OFFSET_STATE_FILE=/shared-data/state/offset_state.json
    volumes:
      - shared-data:/shared-data
    depends_on:
      - volume-init
      - transcription-service
    restart: unless-stopped

  stream-mirroring:
    build:
      context: .
      dockerfile: stream-mirroring/Dockerfile
    env_file:
      - .env
    environment:
      - WEBVTT_SEGMENT_DURATION=10
      # Clock configuration
      - CLOCK_UPDATE_INTERVAL=1800
      - CLOCK_MAX_DRIFT=0.1
      - CLOCK_STATE_FILE=/shared-data/state/clock_state.json
      # Ensure FFmpeg uses consistent parameters
      - FFMPEG_COPYTS=1
      - FFMPEG_START_AT_ZERO=1
      - FFMPEG_SEGMENT_DURATION=10
      # Input URL for the stream
      - INPUT_URL=${HLS_STREAM_URL}
    volumes:
      - shared-data:/shared-data
      - ./scripts:/app/scripts
    depends_on:
      - volume-init
      - caption-generator
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - shared-data:/shared-data
    depends_on:
      - volume-init
      - stream-mirroring
    restart: unless-stopped

volumes:
  shared-data:
    driver: local 