services:
  rainscribe:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    environment:
      - GLADIA_API_KEY=${GLADIA_API_KEY}
      - STREAM_URL=${STREAM_URL:-https://wl.tvrain.tv/transcode/ses_1080p/playlist.m3u8}
      - HTTP_PORT=8080
      - MIN_CUES=2
      - DEBUG_MESSAGES=${DEBUG_MESSAGES:-false}
      - OUTPUT_DIR=/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s