version: '3'

services:
  rainscribe:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
      - GLADIA_API_KEY=${GLADIA_API_KEY}
      - STREAM_URL=${STREAM_URL:-https://wl.tvrain.tv/transcode/ses_1080p/playlist.m3u8}
      - HTTP_PORT=8080
      - MIN_CUES=2
      - OUTPUT_DIR=/app/output 