services:
  rainscribe:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./output:/app/output
    environment:
      - GLADIA_API_KEY=${GLADIA_API_KEY}
      - STREAM_URL=${STREAM_URL:-https://wl.tvrain.tv/transcode/ses_1080p/playlist.m3u8}
      - HTTP_PORT=8080
      - SEGMENT_DURATION=10
      - WINDOW_SIZE=10
      - OUTPUT_DIR=/app/output
      # Logging configuration
      - CAPTIONS_LOG_LEVEL=${CAPTIONS_LOG_LEVEL:-INFO}
      - SYSTEM_LOG_LEVEL=${SYSTEM_LOG_LEVEL:-INFO}
      - TRANSCRIPTION_LOG_LEVEL=${TRANSCRIPTION_LOG_LEVEL:-ERROR}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Improve container performance
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Add logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"