apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rainscribe.fullname" . }}-caption-generator
  labels:
    {{- include "rainscribe.labels" . | nindent 4 }}
    app.kubernetes.io/component: caption-generator
spec:
  replicas: {{ .Values.captionGenerator.replicaCount }}
  selector:
    matchLabels:
      {{- include "rainscribe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: caption-generator
  template:
    metadata:
      labels:
        {{- include "rainscribe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: caption-generator
    spec:
      containers:
        - name: caption-generator
          image: "{{ .Values.captionGenerator.image.repository }}:{{ .Values.captionGenerator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.captionGenerator.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.captionGenerator.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.global.env.SHARED_VOLUME_PATH }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ include "rainscribe.fullname" . }}-shared-data 