apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-audio-extractor
  labels:
    {{- include "rainscribe.labels" . | nindent 4 }}
    app.kubernetes.io/component: audio-extractor
spec:
  replicas: {{ .Values.audioExtractor.replicaCount }}
  selector:
    matchLabels:
      {{- include "rainscribe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: audio-extractor
  template:
    metadata:
      labels:
        {{- include "rainscribe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: audio-extractor
    spec:
      containers:
        - name: audio-extractor
          image: "{{ .Values.audioExtractor.image.repository }}:{{ .Values.audioExtractor.image.tag }}"
          imagePullPolicy: {{ .Values.audioExtractor.image.pullPolicy }}
          env:
            {{- include "rainscribe.env" . | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.global.env.SHARED_VOLUME_PATH }}
          resources:
            {{- toYaml .Values.audioExtractor.resources | nindent 12 }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-data 