apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rainscribe.fullname" . }}-volume-init
  labels:
    {{- include "rainscribe.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "rainscribe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: volume-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: volume-init
          image: "{{ .Values.volumeInit.image.repository }}:{{ .Values.volumeInit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.volumeInit.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.global.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.volumeInit.resources | nindent 12 }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.global.env.SHARED_VOLUME_PATH }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ include "rainscribe.fullname" . }}-shared-data 