{{- if .Values.sharedVolume.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-volume-init
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-volume-init
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-volume-init
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: volume-init
          image: "{{ .Values.volumeInit.image.repository }}:{{ .Values.volumeInit.image.tag }}"
          imagePullPolicy: {{ .Values.volumeInit.image.pullPolicy }}
          env:
            - name: SHARED_VOLUME_PATH
              value: {{ .Values.global.env.SHARED_VOLUME_PATH | quote }}
            - name: TRANSCRIPTION_LANGUAGE
              value: {{ .Values.global.env.TRANSCRIPTION_LANGUAGE | quote }}
            - name: TRANSLATION_LANGUAGES
              value: {{ .Values.global.env.TRANSLATION_LANGUAGES | quote }}
          volumeMounts:
            - name: shared-data
              mountPath: {{ .Values.global.env.SHARED_VOLUME_PATH }}
          resources:
            {{- toYaml .Values.volumeInit.resources | nindent 12 }}
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-shared-data
{{- end }} 